name: pixel_color_image
description: >
  Pick the pixel color of a image.
  Super simple and Easy to use.
version: 1.1.1
homepage: https://github.com/rbdog/pixel_color_image
repository: https://github.com/rbdog/pixel_color_image

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
