name: pixel_color_picker
description: >
  Pick the pixel color of a image.
  Super simple and Easy to use.
version: 1.0.0
homepage: https://github.com/rbdog/pixel_color_picker
repository: https://github.com/rbdog/pixel_color_picker

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
